In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("movie_metadata.csv")

In [3]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [4]:
df.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [5]:
# Data Reduction
# Remove/reduce unnecessary attributes from dataframe
subset = df[['movie_title','num_user_for_reviews','genres','imdb_score','budget','gross','duration','title_year','language','actor_1_name']]
subset.head()

,movie_title,num_user_for_reviews,genres,imdb_score,budget,gross,duration,title_year,language,actor_1_name
0,Avatar,3054.0,Action|Adventure|Fantasy|Sci-Fi,7.9,237000000.0,760505847.0,178.0,2009.0,English,CCH Pounder
1,Pirates of the Caribbean: At World's End,1238.0,Action|Adventure|Fantasy,7.1,300000000.0,309404152.0,169.0,2007.0,English,Johnny Depp
2,Spectre,994.0,Action|Adventure|Thriller,6.8,245000000.0,200074175.0,148.0,2015.0,English,Christoph Waltz
3,The Dark Knight Rises,2701.0,Action|Thriller,8.5,250000000.0,448130642.0,164.0,2012.0,English,Tom Hardy
4,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,Documentary,7.1,NaN,NaN,NaN,NaN,NaN,Doug Walker

In [6]:
# Data Cleaning
# Find missing values
subset.isnull().sum()

movie_title               0
num_user_for_reviews     21
genres                    0
imdb_score                0
budget                  492
gross                   884
duration                 15
title_year              108
language                 12
actor_1_name              7
dtype: int64

In [7]:
# Define function for median
def impute_median(series):
    return series.fillna(series.median())

In [8]:
# Fill missing value of integer column with median
subset.title_year=df['title_year'].transform(impute_median)
subset.budget=df['budget'].transform(impute_median)
subset.gross=df['gross'].transform(impute_median)
subset.duration=df['duration'].transform(impute_median)

C:\Users\HP\anaconda3\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [9]:
subset.isnull().sum()

movie_title              0
num_user_for_reviews    21
genres                   0
imdb_score               0
budget                   0
gross                    0
duration                 0
title_year               0
language                12
actor_1_name             7
dtype: int64

In [10]:
# Fill missing value of integer column with mode
subset['language'] = subset['language'].fillna(subset['language'].mode()[0])
subset['actor_1_name'] = subset['actor_1_name'].fillna(subset['actor_1_name'].mode()[0])

C:\Users\HP\AppData\Local\Temp/ipykernel_10940/1464366959.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['language'] = subset['language'].fillna(subset['language'].mode()[0])
C:\Users\HP\AppData\Local\Temp/ipykernel_10940/1464366959.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['actor_1_name'] = subset['actor_1_name'].fillna(subset['actor_1_name'].mode()[0])

In [11]:
subset.isnull().sum()

movie_title              0
num_user_for_reviews    21
genres                   0
imdb_score               0
budget                   0
gross                    0
duration                 0
title_year               0
language                 0
actor_1_name             0
dtype: int64

In [12]:
# Read another dataset with atleast one same attribute as previous dataset
df2 = pd.read_csv('main_data.csv')

In [13]:
df2.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...

In [14]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6010 entries, 0 to 6009
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   director_name  6010 non-null   object
 1   actor_1_name   6010 non-null   object
 2   actor_2_name   6010 non-null   object
 3   actor_3_name   6010 non-null   object
 4   genres         6010 non-null   object
 5   movie_title    6010 non-null   object
 6   comb           6010 non-null   object
dtypes: object(7)
memory usage: 328.8+ KB

In [15]:
# Data Reduction 
subset1 = df2[['movie_title','director_name','actor_2_name','actor_3_name']]
subset1.head()

,movie_title,director_name,actor_2_name,actor_3_name
0,avatar,James Cameron,Joel David Moore,Wes Studi
1,pirates of the caribbean: at world's end,Gore Verbinski,Orlando Bloom,Jack Davenport
2,spectre,Sam Mendes,Rory Kinnear,Stephanie Sigman
3,the dark knight rises,Christopher Nolan,Christian Bale,Joseph Gordon-Levitt
4,star wars: episode vii - the force awakensÂ ...,Doug Walker,Rob Walker,unknown

In [16]:
display(subset,subset1)

,movie_title,num_user_for_reviews,genres,imdb_score,budget,gross,duration,title_year,language,actor_1_name
0,Avatar,3054.0,Action|Adventure|Fantasy|Sci-Fi,7.9,237000000.0,760505847.0,178.0,2009.0,English,CCH Pounder
1,Pirates of the Caribbean: At World's End,1238.0,Action|Adventure|Fantasy,7.1,300000000.0,309404152.0,169.0,2007.0,English,Johnny Depp
2,Spectre,994.0,Action|Adventure|Thriller,6.8,245000000.0,200074175.0,148.0,2015.0,English,Christoph Waltz
3,The Dark Knight Rises,2701.0,Action|Thriller,8.5,250000000.0,448130642.0,164.0,2012.0,English,Tom Hardy
4,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,Documentary,7.1,20000000.0,25517500.0,103.0,2005.0,English,Doug Walker
...,...,...,...,...,...,...,...,...,...,...
5038,Signed Sealed Delivered,6.0,Comedy|Drama,7.7,20000000.0,25517500.0,87.0,2013.0,English,Eric Mabius
5039,The Following,359.0,Crime|Drama|Mystery|Thriller,7.5,20000000.0,25517500.0,43.0,2005.0,English,Natalie Zea
5040,A Plague So Pleasant,3.0,Drama|Horror|Thriller,6.3,1400.0,25517500.0,76.0,2013.0,English,Eva Boehnke
5041,Shanghai Calling,9.0,Comedy|Drama|Romance,6.3,20000000.0,10443.0,100.0,2012.0,English,Alan Ruck
5042,My Date with Drew,84.0,Documentary,6.6,1100.0,85222.0,90.0,2004.0,English,John August

,movie_title,director_name,actor_2_name,actor_3_name
0,avatar,James Cameron,Joel David Moore,Wes Studi
1,pirates of the caribbean: at world's end,Gore Verbinski,Orlando Bloom,Jack Davenport
2,spectre,Sam Mendes,Rory Kinnear,Stephanie Sigman
3,the dark knight rises,Christopher Nolan,Christian Bale,Joseph Gordon-Levitt
4,star wars: episode vii - the force awakensÂ ...,Doug Walker,Rob Walker,unknown
...,...,...,...,...
6005,top gun: maverick,Joseph Kosinski,Miles Teller,Jennifer Connelly
6006,the croods 2,Joel Crawford,Emma Stone,Ryan Reynolds
6007,respect,Liesl Tommy,Forest Whitaker,Marlon Wayans
6008,the last duel,Ridley Scott,Adam Driver,Jodie Comer
6009,news of the world,Paul Greengrass,Helena Zengel,Neil Sandilands

In [17]:
# Data Integration
# Integrate/merge two dataframe
subset2 = pd.merge(subset,subset1,left_index=True, right_index=True)

In [18]:
subset2.head(20)

,movie_title_x,num_user_for_reviews,genres,imdb_score,budget,gross,duration,title_year,language,actor_1_name,movie_title_y,director_name,actor_2_name,actor_3_name
0,Avatar,3054.0,Action|Adventure|Fantasy|Sci-Fi,7.9,237000000.0,760505847.0,178.0,2009.0,English,CCH Pounder,avatar,James Cameron,Joel David Moore,Wes Studi
1,Pirates of the Caribbean: At World's End,1238.0,Action|Adventure|Fantasy,7.1,300000000.0,309404152.0,169.0,2007.0,English,Johnny Depp,pirates of the caribbean: at world's end,Gore Verbinski,Orlando Bloom,Jack Davenport
2,Spectre,994.0,Action|Adventure|Thriller,6.8,245000000.0,200074175.0,148.0,2015.0,English,Christoph Waltz,spectre,Sam Mendes,Rory Kinnear,Stephanie Sigman
3,The Dark Knight Rises,2701.0,Action|Thriller,8.5,250000000.0,448130642.0,164.0,2012.0,English,Tom Hardy,the dark knight rises,Christopher Nolan,Christian Bale,Joseph Gordon-Levitt
4,Star Wars: Episode VII - The Force AwakensÂ ...,NaN,Documentary,7.1,20000000.0,25517500.0,103.0,2005.0,English,Doug Walker,star wars: episode vii - the force awakensÂ ...,Doug Walker,Rob Walker,unknown
5,John Carter,738.0,Action|Adventure|Sci-Fi,6.6,263700000.0,73058679.0,132.0,2012.0,English,Daryl Sabara,john carter,Andrew Stanton,Samantha Morton,Polly Walker
6,Spider-Man 3,1902.0,Action|Adventure|Romance,6.2,258000000.0,336530303.0,156.0,2007.0,English,J.K. Simmons,tangled,Nathan Greno,Donna Murphy,M.C. Gainey
7,Tangled,387.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,7.8,260000000.0,200807262.0,100.0,2010.0,English,Brad Garrett,avengers: age of ultron,Joss Whedon,Robert Downey Jr.,Scarlett Johansson
8,Avengers: Age of Ultron,1117.0,Action|Adventure|Sci-Fi,7.5,250000000.0,458991599.0,141.0,2015.0,English,Chris Hemsworth,harry potter and the half-blood prince,David Yates,Daniel Radcliffe,Rupert Grint
9,Harry Potter and the Half-Blood Prince,973.0,Adventure|Family|Fantasy|Mystery,7.5,250000000.0,301956980.0,153.0,2009.0,English,Alan Rickman,batman v superman: dawn of justice,Zack Snyder,Lauren Cohan,Alan D. Purwin
10,Batman v Superman: Dawn of Justice,3018.0,Action|Adventure|Sci-Fi,6.9,250000000.0,330249062.0,183.0,2016.0,English,Henry Cavill,superman returns,Bryan Singer,Marlon Brando,Frank Langella
11,Superman Returns,2367.0,Action|Adventure|Sci-Fi,6.1,209000000.0,200069408.0,169.0,2006.0,English,Kevin Spacey,quantum of solace,Marc Forster,Mathieu Amalric,Rory Kinnear
12,Quantum of Solace,1243.0,Action|Adventure,6.7,200000000.0,168368427.0,106.0,2008.0,English,Giancarlo Giannini,pirates of the caribbean: dead man's chest,Gore Verbinski,Orlando Bloom,Jack Davenport
13,Pirates of the Caribbean: Dead Man's Chest,1832.0,Action|Adventure|Fantasy,7.3,225000000.0,423032628.0,151.0,2006.0,English,Johnny Depp,the lone ranger,Gore Verbinski,Ruth Wilson,Tom Wilkinson
14,The Lone Ranger,711.0,Action|Adventure|Western,6.5,215000000.0,89289910.0,150.0,2013.0,English,Johnny Depp,man of steel,Zack Snyder,Christopher Meloni,Harry Lennix
15,Man of Steel,2536.0,Action|Adventure|Fantasy|Sci-Fi,7.2,225000000.0,291021565.0,143.0,2013.0,English,Henry Cavill,the chronicles of narnia: prince caspian,Andrew Adamson,Pierfrancesco Favino,DamiÃ¡n AlcÃ¡zar
16,The Chronicles of Narnia: Prince Caspian,438.0,Action|Adventure|Family|Fantasy,6.6,225000000.0,141614023.0,150.0,2008.0,English,Peter Dinklage,pirates of the caribbean: on stranger tides,Rob Marshall,Sam Claflin,Stephen Graham
17,The Avengers,1722.0,Action|Adventure|Sci-Fi,8.1,220000000.0,623279547.0,173.0,2012.0,English,Chris Hemsworth,men in black 3,Barry Sonnenfeld,Michael Stuhlbarg,Nicole Scherzinger
18,Pirates of the Caribbean: On Stranger Tides,484.0,Action|Adventure|Fantasy,6.7,250000000.0,241063875.0,136.0,2011.0,English,Johnny Depp,the hobbit: the battle of the five armies,Peter Jackson,Adam Brown,James Nesbitt
19,Men in Black 3,341.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,6.8,225000000.0,179020854.0,106.0,2012.0,English,Will Smith,the amazing spider-man,Marc Webb,Andrew Garfield,Chris Zylka

In [19]:
# Data Transformation
subset2.to_excel('merge.xlsx')